sklep/urls.py
from django.conf.urls import patterns, url

from sklep import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
	url(r'^kojot/$', views.kojot, name='kojot'),
    url(r'^(?P<requested_id>\d+)/$', views.kategoria, name='kategoria'),
    url(r'^produkty/(?P<requested_id>\d+)/$', views.produkt, name='produkt'),
    url(r'^produkty/(?P<requested_id>\d+)/dokoszyka$', views.dokoszyka, name='dokoszyka'),
	url(r'^kontakt/$', views.kontakt, name='kontakt'),
	url(r'^osklepie/$', views.osklepie, name='osklepie'),
	url(r'^zaloguj/$', views.zaloguj, name='zaloguj'),
	url(r'^nowekonto/$', views.nowekonto, name='nowekonto'),
	url(r'^koszyk/$', views.koszyk, name='koszyk'),
	url(r'^kupze/$', views.kupze, name='kupze'),
	url(r'^kupione/$', views.kupione, name='kupione'),
	url(r'^wyloguj/$', 'django.contrib.auth.views.logout', { 'next_page': '/sklep' }),
)

sklepDjango/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^sklep/', include('sklep.urls')),
	url(r'^kojot/', include('sklep.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

sklep/models.py
from django.db import models
from django.contrib.auth.models import User

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.choice_text

class Kategoria(models.Model):
    id = models.AutoField(primary_key=True)
    level = models.IntegerField(default=0)
    nazwa_kat = models.CharField('nazwa kategorii',max_length=100)
    parrent = models.ForeignKey('self', null=True)
    def __unicode__(self):
        return self.nazwa_kat

class Produkt(models.Model):
    nazwa_prod = models.CharField('nazwa produktu',max_length=100)
    opis_prod = models.CharField('opis produktu',max_length=300)
    kategoria = models.ForeignKey(Kategoria)
    cena = models.IntegerField(default=0)
    def __unicode__(self):
        return self.nazwa_prod

class Koszyk(models.Model):
    produkty = models.ManyToManyField(Produkt, through='ProduktKoszykowy')
    uzytkownik = models.OneToOneField(User, related_name='koszyk')

class ProduktKoszykowy(models.Model):
    produkt = models.ForeignKey(Produkt)
    koszyk = models.ForeignKey(Koszyk)
    ile = models.IntegerField()

sklep/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.contrib.auth import authenticate
from sklep.models import Kategoria, Produkt, Koszyk, ProduktKoszykowy
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django import forms
from django.core.urlresolvers import reverse

def index(request):
	template = loader.get_template('sklep/index.html')
	context = RequestContext(request)
	return HttpResponse(template.render(context))


def kojot(request):
	return HttpResponse("Tutaj kojot pszemek.")


def parsuj_kategorie(rodzic, wynik):
	for kat in rodzic.kategoria_set.all():
		wynik += kat.produkt_set.all()
		parsuj_kategorie(kat, wynik)


def kategoria(request, requested_id):

	wybranaKategoria = Kategoria.objects.get(id=requested_id)
	produkt_list = list(wybranaKategoria.produkt_set.order_by('nazwa_prod'))

	parsuj_kategorie(wybranaKategoria, produkt_list)

	template = loader.get_template('sklep/produkty.html')
	context = RequestContext(request, {
		'produkt_list': produkt_list,
		'wybranaKategoria' : wybranaKategoria,
	})
	return HttpResponse(template.render(context))

def produkt(request, requested_id):
	prod = Produkt.objects.get(id=requested_id)

	template = loader.get_template('sklep/detail.html')
	context = RequestContext(request, {
		'prod' : prod,
	})
	return HttpResponse(template.render(context))

def kontakt(request):

	template = loader.get_template('sklep/kontakt.html')
	context = RequestContext(request)
	return HttpResponse(template.render(context))

def osklepie(request):

	template = loader.get_template('sklep/osklepie.html')
	context = RequestContext(request)
	return HttpResponse(template.render(context))

def zaloguj(request):


	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)

		if form.is_valid():
			login(request, form.get_user())
			return redirect('index')
		else:
			pass
	else:
		form = AuthenticationForm()


	template = loader.get_template('sklep/zaloguj.html')
	context = RequestContext(request, {
		'form': form
	})

	return HttpResponse(template.render(context))

def nowekonto(request):

	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			new_user = form.save()
			return HttpResponseRedirect('/sklep')
	else:
		form = UserCreationForm()


	template = loader.get_template('sklep/nowekonto.html')
	context = RequestContext(request, {
		'form': form
	})
	return HttpResponse(template.render(context))


@login_required
def dokoszyka(request, requested_id):
	if request.method == 'POST':
		prod = Produkt.objects.get(id=requested_id)
		try:
			kosz = Koszyk.objects.get(uzytkownik=request.user)
		except Koszyk.DoesNotExist:
			kosz = Koszyk.objects.create(uzytkownik=request.user)

		try:
			wkoszyku = ProduktKoszykowy.objects.get(koszyk=kosz, produkt=prod)
			wkoszyku.ile += 1
			wkoszyku.save()
		except ProduktKoszykowy.DoesNotExist:
			ProduktKoszykowy.objects.create(koszyk=kosz, produkt=prod, ile=1)

		return redirect('produkt', requested_id=requested_id)

	return HttpResponse()

@login_required
def koszyk(request):
	try:
		kosz = Koszyk.objects.get(uzytkownik=request.user)
	except Koszyk.DoesNotExist:
		kosz = Koszyk.objects.create(uzytkownik=request.user)

	template = loader.get_template('sklep/koszyk.html')
	context = RequestContext(request, {
		'kosz': kosz
	})
	return HttpResponse(template.render(context))


class KupzeForm(forms.Form):
    imie = forms.CharField()
    nazwisko = forms.CharField()
    adres = forms.CharField()


@login_required
def kupze(request):
	try:
		kosz = Koszyk.objects.get(uzytkownik=request.user)
	except Koszyk.DoesNotExist:
		kosz = Koszyk.objects.create(uzytkownik=request.user)

	if request.method == 'POST':
		form = KupzeForm(request.POST)
		if form.is_valid():
			ProduktKoszykowy.objects.filter(koszyk=kosz).delete()
			return HttpResponseRedirect(reverse('kupione'))
	else:
		form = KupzeForm()

	template = loader.get_template('sklep/kupze.html')
	context = RequestContext(request, {
		'kosz': kosz,
		'form': form
	})
	return HttpResponse(template.render(context))


@login_required
def kupione(request):
	template = loader.get_template('sklep/kupione.html')
	context = RequestContext(request)
	return HttpResponse(template.render(context))

sklep/templates/produkty_old.html
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript" src="/static/jquery.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/sklep.css" />
	<link rel="stylesheet" type="test/css" href="/static/css/bootstrap.css" />
</head>
<body>
	{% if produkt_list %}
		<p>
			Lista dostępnych produktów w kategorii: <strong>{{ wybranaKategoria.nazwa_kat }}</strong>
		</p>
		<hr />
		<ul>
		{% for produkt in produkt_list %}
			<li><a href="/sklep/produkty/{{ produkt.id }}/">{{ produkt.nazwa_prod }}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>Ni ma dostępnych produktów</p>
	{% endif %}
</body>
</html>

sklep/templates/sklep/detail.html
{% include "header.html" %}

	<p>Szczegóły produktu:</p>
	<hr />
	{% if prod %}
	<p>Patrzysz na produkt o id: {{ prod.id }}. <br><br> Opis produktu: <br> {{ prod.opis_prod }}.</p>
	<form method="POST" action="{% url 'dokoszyka' prod.id %}">
		{% csrf_token %}
		<button type="submit" class="btn btn-lg btn-primary">Załaduj do koszyka</button>
	</form>
	{% else %}
		<p>Ni ma</p>
	{% endif %}

{% include "footer.html" %}

sklep/templates/sklep/footer.html
</div> <!-- /container -->
<div>

</div>
</body>

</html>

sklep/templates/sklep/header.html
<!DOCTYPE html>
<html>

<head>
	<!-- Dla bootstrapa -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">


	<script type="text/javascript" src="/static/jquery.js"></script>
	<script type="text/javascript" src="/static/js/bootstrap.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css" />
	<link rel="stylesheet" type="text/css" href="/static/css/bootstrap-cerulean.css" />

	<title>Sklep internetowy</title>
</head>

<body>
<div class="container">

	<!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/sklep">Sklep internetowy</a>
        </div>
        <div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">


			<!-- TODO -->


			<li class="active"><a href="/sklep">Strona główna</a></li>
			<li class="dropdown">
			  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kategorie <b class="caret"></b></a>
			  <ul class="dropdown-menu">

				{% if kategoria_list %}
					{% for poziom, kategoria in kategoria_list %}
						<li style="padding-left: {% widthratio poziom 1 2 %}em"><a href="/sklep/{{ kategoria.id }}/">{{ kategoria.nazwa_kat }}</a></li>
					{% endfor %}
				{% else %}
					<li>Nie ma</li>
				{% endif %}

				<!--
				<li class="divider"></li>
				<li class="dropdown-header">Nav header</li>
				-->
			  </ul>
			</li>
			<li><a href="/sklep/osklepie/">O sklepie</a></li>
			<li><a href="/sklep/kontakt/">Kontakt</a></li>
			</ul>
				<ul class="nav navbar-nav navbar-right">



					<!-- TODO -->


            		{% if not user.is_authenticated %}
						<li><a href="/sklep/zaloguj/">Zaloguj</a></li>
					{% else %}
						<li><a href="/sklep/koszyk/">Mój koszyk</a></li>
						<li><a href="/sklep/wyloguj/">Wyloguj</a></li>
					{% endif %}
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>

sklep/templates/sklep/index.html
{% include "header.html" %}

	<div class="jumbotron">
		<h1>Witamy w sklepie internetowym</h1>
		<br>
		<p>Sklep internetowy na zaliczenie Organizacji Usług Komercyjnych w Internecie</p>
		<p></p>
		<br>


        {% if not user.is_authenticated %}
			<p>
				<a class="btn btn-lg btn-primary" href="/sklep/nowekonto/">Utwórz konto &raquo</a>
			</p>
		{% endif %}
	</div>

	<hr />

{% include "footer.html" %}

sklep/templates/sklep/kontakt.html
{% include "header.html" %}

	<div class="jumbotron">
		<h1>Kontakt</h1>
		<br>
		<p>Mateusz Lebioda 94332</p>
		<p>matleb@op.pl</p>


		{% if not user.is_authenticated %}
			<p>
				<a class="btn btn-lg btn-primary" href="/sklep/nowekonto/">Utwórz konto &raquo</a>
			</p>
		{% endif %}
	</div>

	<hr />

{% include "footer.html" %}

sklep/templates/sklep/koszyk.html
{% include "header.html" %}

<div class="jumbotron">
	{% if kosz.produktkoszykowy_set.all %}
		<p>
			Lista produktów w koszyku:
		</p>
		<hr />
		<ul>
		{% for produkt in kosz.produktkoszykowy_set.all %}
			<li><a href="/sklep/produkty/{{ produkt.produkt.id }}/">{{ produkt.produkt.nazwa_prod }}</a> - {{ produkt.ile }}</li>
		{% endfor %}
		</ul>

		<p>
			<a class="btn btn-lg btn-primary" href="/sklep/kupze/">Kup &raquo</a>
		</p>
	{% else %}
		<p>Nie masz nic w koszyku.</p>
	{% endif %}
</div>

{% include "footer.html" %}

sklep/templates/sklep/kupione.html
{% load i18n %}

{% include "header.html" %}

	<div class="jumbotron">
		<h1>Kupione!</h1>
		<br>
		<p>Zlecenie zakupu wykonane.</p>
	</div>

	<hr />

{% include "footer.html" %}

sklep/templates/sklep/kupze.html
{% load i18n %}

{% include "header.html" %}

	<div class="jumbotron">
		<h1>Kup</h1>
		<br>
		<p>
			Takie rzeczy kupujesz:
		</p>
		<hr />
		<ul>
		{% for produkt in kosz.produktkoszykowy_set.all %}
			<li><a href="/sklep/produkty/{{ produkt.produkt.id }}/">{{ produkt.produkt.nazwa_prod }}</a> - {{ produkt.ile }}</li>
		{% endfor %}
		</ul>

		<p>Podaj dane do wysłania kupionych produktów</p>

	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<button type="submit" class="btn btn-lg btn-primary">Kupuj</button>
	</form>

	</div>

	<hr />

{% include "footer.html" %}

sklep/templates/sklep/nowekonto.html
{% load i18n %}

{% include "header.html" %}

	<div class="jumbotron">
		<h1>Utwórz konto</h1>
		<br>
		<p>Tutaj robisz nowe konto</p>
		<p>Podaj dane</p>

	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<button type="submit" class="btn btn-lg btn-primary">Utwórz konto</button>
	</form>

	</div>

	<hr />

{% include "footer.html" %}

sklep/templates/sklep/osklepie.html
{% include "header.html" %}

	<div class="jumbotron">
		<h1>O sklepie</h1>
		<br>
		<p>Sklep na zaliczenie Organizacji Usług Komercyjnych w Internecie</p>

		{% if not user.is_authenticated %}
			<p>
				<a class="btn btn-lg btn-primary" href="/sklep/nowekonto/">Utwórz konto &raquo</a>
			</p>
			{% endif %}
	</div>

	<hr />

{% include "footer.html" %}

sklep/templates/sklep/produkty.html
{% include "header.html" %}

<div class="jumbotron">
	{% if produkt_list %}
		<p>
			Lista dostępnych produktów w kategorii: <strong>{{ wybranaKategoria.nazwa_kat }}</strong>
		</p>
		<hr />
		<ul>
		{% for produkt in produkt_list %}
			<li><a href="/sklep/produkty/{{ produkt.id }}/">{{ produkt.nazwa_prod }}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>Ni ma dostępnych produktów</p>
	{% endif %}
</div>

{% include "footer.html" %}

sklep/templates/sklep/zaloguj.html
{% include "header.html" %}

	<div class="jumbotron">

		{% if not user.is_authenticated %}
			<h1>Zaloguj</h1>
			<br>
			<p>Tutaj sie musisz zalogować</p>
			

			{% block content %}
			{% if form.errors %}
			<p>Your username and password didn't match. Please try again.</p>
			{% endif %}
			<form action="" method="post">
				{% csrf_token %}
				<table>
					{{ form.as_table }}
				</table>
				<button type="submit" class="btn btn-lg btn-primary">Zaloguj</button>
			</form>

			{% endblock %}


			<p>
			<br>
				<a class="btn btn-lg btn-primary" href="/sklep/nowekonto/">Utwórz konto &raquo</a>
			</p>
		{% else %}
			Jesteś zalogowany ! <a href="/sklep/wyloguj/">Wyloguj się.</a>
		{% endif %}
	</div>

	<hr />

{% include "footer.html" %}